# Generated by Django 3.0.2 on 2020-01-31 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_quiz', '0002_auto_20200130_0852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reporting',
        ),
    ]
