# Generated by Django 3.0.2 on 2020-02-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_quiz', '0004_auto_20200207_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='answertime',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('selectedoption', models.CharField(max_length=1000)),
                ('timetaken', models.IntegerField()),
            ],
        ),
    ]
